[workspace]
members = [
    "api",
    "api-test",
    "impl-native-tls",
    "impl-openssl",
    "impl-rustls",
    "impl-security-framework",
    "impl-stub",
    "examples",
    "interop",
    "ci-gen",
    "test-cert-gen",
]

[patch.crates-io]
